export const US_CITIES = [
  "Redlands, CA",
  "Loma Linda, CA",
  "Highland, CA",
  "Yucaipa, CA",
  "Grand Terrace, CA",
  "Colton, CA",
  "Rialto, CA",
  "Upland, CA",
  "Claremont, CA",
  "Burbank, CA",
  "Costa Mesa, CA",
  "Newport Beach, CA",
  "Santa Monica, CA",
  "Birmingham, AL",
  "Montgomery, AL",
  "Huntsville, AL",
  "Mobile, AL",
  "Tuscaloosa, AL",
  "Hoover, AL",
  "Auburn, AL",
  "Dothan, AL",
  "Decatur, AL",
  "Madison, AL",
  "Florence, AL",
  "Gadsden, AL",
  "Anchorage, AK",
  "Fairbanks, AK",
  "Juneau, AK",
  "Sitka, AK",
  "Ketchikan, AK",
  "Wasilla, AK",
  "Kenai, AK",
  "Kodiak, AK",
  "Palmer, AK",
  "Bethel, AK",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Mesa, AZ",
  "Chandler, AZ",
  "Scottsdale, AZ",
  "Glendale, AZ",
  "Gilbert, AZ",
  "Tempe, AZ",
  "Peoria, AZ",
  "Surprise, AZ",
  "Yuma, AZ",
  "Flagstaff, AZ",
  "Avondale, AZ",
  "Goodyear, AZ",
  "Lake Havasu City, AZ",
  "Buckeye, AZ",
  "Prescott, AZ",
  "Little Rock, AR",
  "Fort Smith, AR",
  "Fayetteville, AR",
  "Springdale, AR",
  "Jonesboro, AR",
  "Rogers, AR",
  "Conway, AR",
  "North Little Rock, AR",
  "Bentonville, AR",
  "Pine Bluff, AR",
  "Hot Springs, AR",
  "Los Angeles, CA",
  "San Diego, CA",
  "San Jose, CA",
  "San Francisco, CA",
  "Fresno, CA",
  "Sacramento, CA",
  "Long Beach, CA",
  "Oakland, CA",
  "Bakersfield, CA",
  "Anaheim, CA",
  "Stockton, CA",
  "Riverside, CA",
  "Santa Ana, CA",
  "Irvine, CA",
  "Chula Vista, CA",
  "Fremont, CA",
  "Santa Clarita, CA",
  "San Bernardino, CA",
  "Modesto, CA",
  "Fontana, CA",
  "Oxnard, CA",
  "Moreno Valley, CA",
  "Huntington Beach, CA",
  "Glendale, CA",
  "Santa Rosa, CA",
  "Ontario, CA",
  "Rancho Cucamonga, CA",
  "Oceanside, CA",
  "Lancaster, CA",
  "Garden Grove, CA",
  "Palmdale, CA",
  "Salinas, CA",
  "Hayward, CA",
  "Corona, CA",
  "Sunnyvale, CA",
  "Pomona, CA",
  "Escondido, CA",
  "Pasadena, CA",
  "Torrance, CA",
  "Orange, CA",
  "Fullerton, CA",
  "Roseville, CA",
  "Visalia, CA",
  "Concord, CA",
  "Santa Clara, CA",
  "Thousand Oaks, CA",
  "Simi Valley, CA",
  "Vallejo, CA",
  "Berkeley, CA",
  "Stanford, CA",
  "Davis, CA",
  "Santa Barbara, CA",
  "Santa Cruz, CA",
  "San Luis Obispo, CA",
  "Palo Alto, CA",
  "San Mateo, CA",
  "Mountain View, CA",
  "Cupertino, CA",
  "Denver, CO",
  "Colorado Springs, CO",
  "Aurora, CO",
  "Fort Collins, CO",
  "Lakewood, CO",
  "Thornton, CO",
  "Arvada, CO",
  "Westminster, CO",
  "Pueblo, CO",
  "Centennial, CO",
  "Boulder, CO",
  "Greeley, CO",
  "Longmont, CO",
  "Loveland, CO",
  "Grand Junction, CO",
  "Broomfield, CO",
  "Castle Rock, CO",
  "Bridgeport, CT",
  "New Haven, CT",
  "Stamford, CT",
  "Hartford, CT",
  "Waterbury, CT",
  "Norwalk, CT",
  "Danbury, CT",
  "New Britain, CT",
  "West Hartford, CT",
  "Greenwich, CT",
  "Hamden, CT",
  "Fairfield, CT",
  "Manchester, CT",
  "Storrs, CT",
  "Wilmington, DE",
  "Dover, DE",
  "Newark, DE",
  "Middletown, DE",
  "Smyrna, DE",
  "Milford, DE",
  "Seaford, DE",
  "Georgetown, DE",
  "Washington, DC",
  "Jacksonville, FL",
  "Miami, FL",
  "Tampa, FL",
  "Orlando, FL",
  "St. Petersburg, FL",
  "Hialeah, FL",
  "Port St. Lucie, FL",
  "Cape Coral, FL",
  "Tallahassee, FL",
  "Fort Lauderdale, FL",
  "Pembroke Pines, FL",
  "Hollywood, FL",
  "Gainesville, FL",
  "Miramar, FL",
  "Coral Springs, FL",
  "Clearwater, FL",
  "Palm Bay, FL",
  "Pompano Beach, FL",
  "West Palm Beach, FL",
  "Lakeland, FL",
  "Boca Raton, FL",
  "Daytona Beach, FL",
  "Sarasota, FL",
  "Pensacola, FL",
  "Kissimmee, FL",
  "Fort Myers, FL",
  "Bradenton, FL",
  "Atlanta, GA",
  "Augusta, GA",
  "Columbus, GA",
  "Macon, GA",
  "Savannah, GA",
  "Athens, GA",
  "Sandy Springs, GA",
  "South Fulton, GA",
  "Roswell, GA",
  "Johns Creek, GA",
  "Warner Robins, GA",
  "Albany, GA",
  "Alpharetta, GA",
  "Marietta, GA",
  "Valdosta, GA",
  "Smyrna, GA",
  "Dunwoody, GA",
  "Statesboro, GA",
  "Honolulu, HI",
  "East Honolulu, HI",
  "Pearl City, HI",
  "Hilo, HI",
  "Kailua, HI",
  "Waipahu, HI",
  "Kaneohe, HI",
  "Kahului, HI",
  "Mililani, HI",
  "Ewa Gentry, HI",
  "Boise, ID",
  "Meridian, ID",
  "Nampa, ID",
  "Idaho Falls, ID",
  "Caldwell, ID",
  "Pocatello, ID",
  "Coeur d'Alene, ID",
  "Twin Falls, ID",
  "Post Falls, ID",
  "Lewiston, ID",
  "Moscow, ID",
  "Rexburg, ID",
  "Chicago, IL",
  "Aurora, IL",
  "Naperville, IL",
  "Joliet, IL",
  "Rockford, IL",
  "Springfield, IL",
  "Elgin, IL",
  "Peoria, IL",
  "Champaign, IL",
  "Urbana, IL",
  "Waukegan, IL",
  "Cicero, IL",
  "Bloomington, IL",
  "Arlington Heights, IL",
  "Evanston, IL",
  "Decatur, IL",
  "Schaumburg, IL",
  "Bolingbrook, IL",
  "Palatine, IL",
  "Skokie, IL",
  "Normal, IL",
  "Carbondale, IL",
  "DeKalb, IL",
  "Indianapolis, IN",
  "Fort Wayne, IN",
  "Evansville, IN",
  "South Bend, IN",
  "Carmel, IN",
  "Fishers, IN",
  "Bloomington, IN",
  "Hammond, IN",
  "Gary, IN",
  "Lafayette, IN",
  "Muncie, IN",
  "Terre Haute, IN",
  "Kokomo, IN",
  "Noblesville, IN",
  "Anderson, IN",
  "Greenwood, IN",
  "West Lafayette, IN",
  "Des Moines, IA",
  "Cedar Rapids, IA",
  "Davenport, IA",
  "Sioux City, IA",
  "Iowa City, IA",
  "Waterloo, IA",
  "Ames, IA",
  "West Des Moines, IA",
  "Council Bluffs, IA",
  "Ankeny, IA",
  "Dubuque, IA",
  "Urbandale, IA",
  "Cedar Falls, IA",
  "Wichita, KS",
  "Overland Park, KS",
  "Kansas City, KS",
  "Olathe, KS",
  "Topeka, KS",
  "Lawrence, KS",
  "Shawnee, KS",
  "Manhattan, KS",
  "Lenexa, KS",
  "Salina, KS",
  "Hutchinson, KS",
  "Louisville, KY",
  "Lexington, KY",
  "Bowling Green, KY",
  "Owensboro, KY",
  "Covington, KY",
  "Richmond, KY",
  "Georgetown, KY",
  "Florence, KY",
  "Hopkinsville, KY",
  "Nicholasville, KY",
  "Elizabethtown, KY",
  "Frankfort, KY",
  "New Orleans, LA",
  "Baton Rouge, LA",
  "Shreveport, LA",
  "Lafayette, LA",
  "Lake Charles, LA",
  "Kenner, LA",
  "Bossier City, LA",
  "Monroe, LA",
  "Alexandria, LA",
  "Houma, LA",
  "New Iberia, LA",
  "Ruston, LA",
  "Portland, ME",
  "Lewiston, ME",
  "Bangor, ME",
  "South Portland, ME",
  "Auburn, ME",
  "Biddeford, ME",
  "Sanford, ME",
  "Saco, ME",
  "Augusta, ME",
  "Orono, ME",
  "Brunswick, ME",
  "Baltimore, MD",
  "Frederick, MD",
  "Rockville, MD",
  "Gaithersburg, MD",
  "Bowie, MD",
  "Hagerstown, MD",
  "Annapolis, MD",
  "College Park, MD",
  "Salisbury, MD",
  "Laurel, MD",
  "Bethesda, MD",
  "Silver Spring, MD",
  "Towson, MD",
  "Boston, MA",
  "Worcester, MA",
  "Springfield, MA",
  "Cambridge, MA",
  "Lowell, MA",
  "Brockton, MA",
  "Quincy, MA",
  "Lynn, MA",
  "New Bedford, MA",
  "Fall River, MA",
  "Newton, MA",
  "Somerville, MA",
  "Lawrence, MA",
  "Framingham, MA",
  "Waltham, MA",
  "Amherst, MA",
  "Northampton, MA",
  "Medford, MA",
  "Brookline, MA",
  "Detroit, MI",
  "Grand Rapids, MI",
  "Warren, MI",
  "Sterling Heights, MI",
  "Ann Arbor, MI",
  "Lansing, MI",
  "Flint, MI",
  "Dearborn, MI",
  "Livonia, MI",
  "Troy, MI",
  "Westland, MI",
  "Farmington Hills, MI",
  "Kalamazoo, MI",
  "Wyoming, MI",
  "Southfield, MI",
  "Rochester Hills, MI",
  "East Lansing, MI",
  "Mount Pleasant, MI",
  "Ypsilanti, MI",
  "Minneapolis, MN",
  "Saint Paul, MN",
  "Rochester, MN",
  "Bloomington, MN",
  "Duluth, MN",
  "Brooklyn Park, MN",
  "Plymouth, MN",
  "Woodbury, MN",
  "Lakeville, MN",
  "St. Cloud, MN",
  "Eagan, MN",
  "Maple Grove, MN",
  "Eden Prairie, MN",
  "Mankato, MN",
  "Moorhead, MN",
  "Winona, MN",
  "Jackson, MS",
  "Gulfport, MS",
  "Southaven, MS",
  "Biloxi, MS",
  "Hattiesburg, MS",
  "Olive Branch, MS",
  "Tupelo, MS",
  "Meridian, MS",
  "Greenville, MS",
  "Oxford, MS",
  "Starkville, MS",
  "Kansas City, MO",
  "St. Louis, MO",
  "Springfield, MO",
  "Columbia, MO",
  "Independence, MO",
  "Lee's Summit, MO",
  "O'Fallon, MO",
  "St. Joseph, MO",
  "St. Charles, MO",
  "St. Peters, MO",
  "Blue Springs, MO",
  "Florissant, MO",
  "Joplin, MO",
  "Chesterfield, MO",
  "Jefferson City, MO",
  "Cape Girardeau, MO",
  "Rolla, MO",
  "Billings, MT",
  "Missoula, MT",
  "Great Falls, MT",
  "Bozeman, MT",
  "Butte, MT",
  "Helena, MT",
  "Kalispell, MT",
  "Havre, MT",
  "Anaconda, MT",
  "Miles City, MT",
  "Omaha, NE",
  "Lincoln, NE",
  "Bellevue, NE",
  "Grand Island, NE",
  "Kearney, NE",
  "Fremont, NE",
  "Hastings, NE",
  "Norfolk, NE",
  "Columbus, NE",
  "North Platte, NE",
  "Las Vegas, NV",
  "Henderson, NV",
  "Reno, NV",
  "North Las Vegas, NV",
  "Sparks, NV",
  "Carson City, NV",
  "Fernley, NV",
  "Elko, NV",
  "Mesquite, NV",
  "Boulder City, NV",
  "Manchester, NH",
  "Nashua, NH",
  "Concord, NH",
  "Dover, NH",
  "Rochester, NH",
  "Keene, NH",
  "Portsmouth, NH",
  "Laconia, NH",
  "Lebanon, NH",
  "Hanover, NH",
  "Durham, NH",
  "Newark, NJ",
  "Jersey City, NJ",
  "Paterson, NJ",
  "Elizabeth, NJ",
  "Lakewood, NJ",
  "Edison, NJ",
  "Woodbridge, NJ",
  "Toms River, NJ",
  "Hamilton, NJ",
  "Trenton, NJ",
  "Clifton, NJ",
  "Camden, NJ",
  "Brick, NJ",
  "Cherry Hill, NJ",
  "Passaic, NJ",
  "Union City, NJ",
  "Old Bridge, NJ",
  "Middletown, NJ",
  "Bayonne, NJ",
  "East Orange, NJ",
  "New Brunswick, NJ",
  "Hoboken, NJ",
  "Princeton, NJ",
  "Albuquerque, NM",
  "Las Cruces, NM",
  "Rio Rancho, NM",
  "Santa Fe, NM",
  "Roswell, NM",
  "Farmington, NM",
  "Clovis, NM",
  "Hobbs, NM",
  "Alamogordo, NM",
  "Carlsbad, NM",
  "Gallup, NM",
  "Los Alamos, NM",
  "New York, NY",
  "Buffalo, NY",
  "Rochester, NY",
  "Yonkers, NY",
  "Syracuse, NY",
  "Albany, NY",
  "New Rochelle, NY",
  "Mount Vernon, NY",
  "Schenectady, NY",
  "Utica, NY",
  "White Plains, NY",
  "Hempstead, NY",
  "Troy, NY",
  "Niagara Falls, NY",
  "Binghamton, NY",
  "Ithaca, NY",
  "Poughkeepsie, NY",
  "Stony Brook, NY",
  "Charlotte, NC",
  "Raleigh, NC",
  "Greensboro, NC",
  "Durham, NC",
  "Winston-Salem, NC",
  "Fayetteville, NC",
  "Cary, NC",
  "Wilmington, NC",
  "High Point, NC",
  "Concord, NC",
  "Asheville, NC",
  "Greenville, NC",
  "Gastonia, NC",
  "Apex, NC",
  "Jacksonville, NC",
  "Chapel Hill, NC",
  "Burlington, NC",
  "Boone, NC",
  "Fargo, ND",
  "Bismarck, ND",
  "Grand Forks, ND",
  "Minot, ND",
  "West Fargo, ND",
  "Williston, ND",
  "Dickinson, ND",
  "Mandan, ND",
  "Jamestown, ND",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Toledo, OH",
  "Akron, OH",
  "Dayton, OH",
  "Parma, OH",
  "Canton, OH",
  "Lorain, OH",
  "Hamilton, OH",
  "Youngstown, OH",
  "Springfield, OH",
  "Kettering, OH",
  "Elyria, OH",
  "Lakewood, OH",
  "Cuyahoga Falls, OH",
  "Dublin, OH",
  "Athens, OH",
  "Oxford, OH",
  "Bowling Green, OH",
  "Kent, OH",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Norman, OK",
  "Broken Arrow, OK",
  "Edmond, OK",
  "Lawton, OK",
  "Moore, OK",
  "Midwest City, OK",
  "Enid, OK",
  "Stillwater, OK",
  "Muskogee, OK",
  "Portland, OR",
  "Salem, OR",
  "Eugene, OR",
  "Gresham, OR",
  "Hillsboro, OR",
  "Beaverton, OR",
  "Bend, OR",
  "Medford, OR",
  "Springfield, OR",
  "Corvallis, OR",
  "Albany, OR",
  "Tigard, OR",
  "Lake Oswego, OR",
  "Ashland, OR",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Allentown, PA",
  "Reading, PA",
  "Erie, PA",
  "Upper Darby, PA",
  "Scranton, PA",
  "Bethlehem, PA",
  "Lancaster, PA",
  "Harrisburg, PA",
  "York, PA",
  "State College, PA",
  "Wilkes-Barre, PA",
  "Norristown, PA",
  "Chester, PA",
  "Bryn Mawr, PA",
  "Providence, RI",
  "Cranston, RI",
  "Warwick, RI",
  "Pawtucket, RI",
  "East Providence, RI",
  "Woonsocket, RI",
  "Newport, RI",
  "Kingston, RI",
  "Charleston, SC",
  "Columbia, SC",
  "North Charleston, SC",
  "Mount Pleasant, SC",
  "Rock Hill, SC",
  "Greenville, SC",
  "Summerville, SC",
  "Goose Creek, SC",
  "Sumter, SC",
  "Florence, SC",
  "Spartanburg, SC",
  "Hilton Head Island, SC",
  "Myrtle Beach, SC",
  "Clemson, SC",
  "Sioux Falls, SD",
  "Rapid City, SD",
  "Aberdeen, SD",
  "Brookings, SD",
  "Watertown, SD",
  "Mitchell, SD",
  "Yankton, SD",
  "Pierre, SD",
  "Vermillion, SD",
  "Nashville, TN",
  "Memphis, TN",
  "Knoxville, TN",
  "Chattanooga, TN",
  "Clarksville, TN",
  "Murfreesboro, TN",
  "Franklin, TN",
  "Johnson City, TN",
  "Jackson, TN",
  "Hendersonville, TN",
  "Bartlett, TN",
  "Kingsport, TN",
  "Cookeville, TN",
  "Houston, TX",
  "San Antonio, TX",
  "Dallas, TX",
  "Austin, TX",
  "Fort Worth, TX",
  "El Paso, TX",
  "Arlington, TX",
  "Corpus Christi, TX",
  "Plano, TX",
  "Lubbock, TX",
  "Laredo, TX",
  "Irving, TX",
  "Garland, TX",
  "Frisco, TX",
  "McKinney, TX",
  "Amarillo, TX",
  "Grand Prairie, TX",
  "Brownsville, TX",
  "Killeen, TX",
  "Denton, TX",
  "Mesquite, TX",
  "McAllen, TX",
  "Pasadena, TX",
  "Waco, TX",
  "Carrollton, TX",
  "Midland, TX",
  "Pearland, TX",
  "Abilene, TX",
  "College Station, TX",
  "Round Rock, TX",
  "Richardson, TX",
  "Beaumont, TX",
  "Odessa, TX",
  "Sugar Land, TX",
  "Tyler, TX",
  "San Marcos, TX",
  "Bryan, TX",
  "Salt Lake City, UT",
  "West Valley City, UT",
  "West Jordan, UT",
  "Provo, UT",
  "Orem, UT",
  "Sandy, UT",
  "St. George, UT",
  "Ogden, UT",
  "Layton, UT",
  "South Jordan, UT",
  "Lehi, UT",
  "Logan, UT",
  "Murray, UT",
  "Draper, UT",
  "Burlington, VT",
  "South Burlington, VT",
  "Rutland, VT",
  "Barre, VT",
  "Montpelier, VT",
  "Winooski, VT",
  "St. Albans, VT",
  "Middlebury, VT",
  "Brattleboro, VT",
  "Virginia Beach, VA",
  "Chesapeake, VA",
  "Norfolk, VA",
  "Richmond, VA",
  "Newport News, VA",
  "Alexandria, VA",
  "Hampton, VA",
  "Roanoke, VA",
  "Portsmouth, VA",
  "Suffolk, VA",
  "Lynchburg, VA",
  "Harrisonburg, VA",
  "Charlottesville, VA",
  "Blacksburg, VA",
  "Fairfax, VA",
  "Arlington, VA",
  "Williamsburg, VA",
  "Seattle, WA",
  "Spokane, WA",
  "Tacoma, WA",
  "Vancouver, WA",
  "Bellevue, WA",
  "Kent, WA",
  "Everett, WA",
  "Renton, WA",
  "Spokane Valley, WA",
  "Federal Way, WA",
  "Yakima, WA",
  "Bellingham, WA",
  "Kirkland, WA",
  "Kennewick, WA",
  "Auburn, WA",
  "Pasco, WA",
  "Redmond, WA",
  "Marysville, WA",
  "Pullman, WA",
  "Olympia, WA",
  "Charleston, WV",
  "Huntington, WV",
  "Morgantown, WV",
  "Parkersburg, WV",
  "Wheeling, WV",
  "Weirton, WV",
  "Fairmont, WV",
  "Martinsburg, WV",
  "Milwaukee, WI",
  "Madison, WI",
  "Green Bay, WI",
  "Kenosha, WI",
  "Racine, WI",
  "Appleton, WI",
  "Waukesha, WI",
  "Eau Claire, WI",
  "Oshkosh, WI",
  "Janesville, WI",
  "West Allis, WI",
  "La Crosse, WI",
  "Sheboygan, WI",
  "Wauwatosa, WI",
  "Fond du Lac, WI",
  "Brookfield, WI",
  "Stevens Point, WI",
  "Cheyenne, WY",
  "Casper, WY",
  "Laramie, WY",
  "Gillette, WY",
  "Rock Springs, WY",
  "Sheridan, WY",
  "Green River, WY",
  "Evanston, WY",
  "Jackson, WY",
  "San Juan, PR",
  "Bayamon, PR",
  "Carolina, PR",
  "Ponce, PR",
  "Caguas, PR",
  "Guaynabo, PR",
  "Mayaguez, PR",
  "Remote / All Locations"
];

export const usCities = US_CITIES;
export default US_CITIES;
